### ISSUE TITLE
shovel made in ecoitems cannot be used to make path on grass

### ISSUE THREAD

**Issue by Uharn** [Auxilor/EcoItems#11]
**Describe the bug**
customs shovels miss the ability to create paths on grass blocks

**To Reproduce**
1. create a ecoitem shovel
2. Right clic on a grass block

> the grass block is not changed to path

**Expected behavior**
The grass should become a path

**Server Information (please complete the following information):**
- Version: visible on airplane 1.17 and pufferfish 1.18
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
ecoitem v3.17.3
eco eco-6.20.4

**Comment by Uharn** [comment]
Same for Axes for stripping logs

**Comment by Uharn** [comment]
Same for hoes ;-)

**Comment by WillFP** [comment]
Should be fixed in latest
