### ISSUE TITLE
Old Ecoweapons are not converted to ecoitems

### ISSUE THREAD

**Issue by Uharn** [Auxilor/EcoItems#12]
**Describe the bug**
I made the upgrade from ecoweapons to ecoitems for my tools.
I have recipes that uses tools in recipes
The old ecoweapons tools are not usable into the new ecoitems recipes

**Expected behavior**
There should be a way to convert old ecoweapons to their similar ecoitems, keeping the enchants players added on them

**Server Information (please complete the following information):**
- Version: 1.18 pufferfish
- eco-6.20.4-all.jar
- EcoItems v3.17.3.jar

migrated from ecoweapon 2.1.3

**Additional context**
Some people on discord explained that i should force players to 
1-Remove their enchants (and loose them)
2-Use a 3rd party plugin for trading old to new item

This is not a way to manage proper upgrades, a converter is needed
i have a 300 regular player base and each of of them got at least 5-6 ecoweapons with various enchants in their pockets
Some enchants were very expensive for them (like 3h cascade boss fights to get them)

**Comment by WillFP** [comment]
Fixed
