### ISSUE TITLE
Points system placeholder output disappears after restart

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/EcoItems#14]
**Describe the bug**
When using the point system of eco after a restart when parsing the placeholder to a player the output is a blank message but as soon as he receives points he will see his point balance again

**To Reproduce**
1. Give yourself a weapon that gives points
2. Make sure to have points by doing /papi parse me %ecoitems_points_POINTNAME%
3. restart the server
4. log back on and do /papi parse me %ecoitems_points_POINTNAME% and the output will be a blank message

**Expected behavior**
I should see my balance. 

**Screenshots**
none, but can be provided if needed

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
This server is running Paper version git-Paper-408 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: cc43ba7 on ver/1.17.1)
You are running the latest version

- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
eco: 6.21.1
Ecoitems: 3.17.3

**Additional context**

**Comment by LuluxClient** [comment]
I am now getting mysql errors: https://pastebin.com/r9DbU8w7

**Comment by WillFP** [comment]
Placeholders fixed
