### ISSUE TITLE
Stacking items causes duplication

### ISSUE THREAD

**Issue by casperwtf** [Auxilor/EcoItems#15]
**Describe the bug**
If you are creating a large amount of custom items, you can shift click and the amount of items when crafting and they wont have the proper amounts removed.

**To Reproduce**
1. Go to a crafting table
2. Put custom items used in a crafting recipe in stacks (A size over the crafting size)
3. Shift click when removing the items

**Expected behavior**
When you shift click the crafting recipe out, it is supposed to remove the correct number of items. The rotten flesh and leather both consume 1 item per craft and the barrel consumes 2. The expected outcome when all are in 64 stacks is that there will be 32 of the resulting item given, no barrels in the center are left and the rotten flesh/leather items are reduced to stacks of 32.

**Screenshots**
[A gif showing it in action](https://gyazo.com/069e39fc19cfd1656f079c3383bd9839)

**Server Information (please complete the following information):**
- Version: (output of `/ver` command)
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)

Server Version: git-Purpur-1519
Eco Version: 6.21.1
EcoItems Version: 3.19.0

**Additional context**

**Comment by casperwtf** [comment]
???

**Comment by PrimalPower** [comment]
ye this is still a problem
