### ISSUE TITLE
Support Aurelium Skills mana

### ISSUE THREAD

**Issue by PrimalPower** [Auxilor/EcoItems#16]
Triggered effects can consume Aurelium skills mana. Amount is specified in the effect args probably ‘mana_cost’. There will be condition ‘mana_requirement’ that the player has to have at least a certain amount of mana. This will require the Aurelium Skills plugin.

Alternatively, there could be that you can show one of the points in the action bar along with the Aurelium skills stat and add a activate-at-interval trigger so I can make a system similar to Aurelium Skills mana

**Comment by WillFP** [comment]
Added in latest

**Comment by PrimalPower** [comment]
:)
