### ISSUE TITLE
/ecoitems give command change

### ISSUE THREAD

**Issue by PrimalPower** [Auxilor/EcoItems#20]
If you have a full inventory then /ecoitems give wont give the item

I would like it so if the inventory is full, it will drop the item on the ground where the player is and the item will only be able to be picked up by that player

**Comment by KermX** [comment]
yes please, or just drop on the ground in general

**Comment by casperwtf** [comment]
could just add a
```
  - /ecoitems give <player> <item> <amount> <other shit that might apply>
  - /ecoitems drop <player> <item> <amount> <other shit that might apply>
  - /ecoitems drop <x> <y> <z> <world> <item> <amount> <other shit that might apply>
```

**Comment by PrimalPower** [comment]
Feature added
