### ISSUE TITLE
[BUG] Effect "attack_speed_multiplier" - does not work with a crossbow.

### ISSUE THREAD

**Issue by Futodama** [Auxilor/EcoItems#21]
Effect "attack_speed_multiplier" - does not work with a crossbow.

I wanted to make a Crossbow that gets a 50% recharge boost at night, but when testing the effect does not work out. I tried other values of the acceleration parameter, but it did not lead to anything, the recharge rate does not accelerate in any way.

The reload speed is even inferior to the crossbow with the "quickcharge I" enchantment.

Code:

- id: te_kaatm_arbalet
  baseDamage: 10
  baseAttackSpeed: 4
  effects:
  - id: attack_speed_multiplier
    args:
      multiplier: 1.5
  conditions:
  - id: is_sneaking
    args:
      is_sneaking: true
  - id: is_night
    args:
      is_night: false
  fuels: []
  item:
    item: crossbow unbreaking:1 HIDE_ENCHANTS HIDE_ATTRIBUTES HIDE_POTION_EFFECTS
    displayName: '&5Арбалет Kaatm'
    lore:
    - '&fКаатм, или "Казнь" на языке.'
    - '&fHelwanca, что причисляет оружие'
    - '&fавтоматически к силе Tenebrae ибо'
    - '&fHelwanca - язык народа теней'
    - '&fи существ ночи из мира Waffcarui.'
    - '&f'
    - '&8Увеличевает свою скорострельность'
    - '&8на 50% в ночное время суток.'
    - '&8Также по желанию владельца'
    - '&8заставляет физическое тело'
    - '&8слиться с тенями на короткое время.'
    - '&f'
    craftable: true
    recipe:
    - ecoitems:tenebrae_shard
    - netherite_ingot
    - ecoitems:tenebrae_shard
    - string
    - tripwire_hook
    - string
    - ecoitems:tenebrae_shard
    - stick
    - ecoitems:tenebrae_shard

**Comment by PrimalPower** [comment]
Attack speed is only for swords. The attack speed stat isn’t a range thing. It controls the Cooldown of melee weapoks in 1.9+

**Comment by WillFP** [comment]
PrimalPower is right on the money here
