### ISSUE TITLE
Able to place down items

### ISSUE THREAD

**Issue by Sedri05** [Auxilor/EcoItems#23]
**Describe the bug**
Since the last update you are now able to place done EcoItems

**To Reproduce**
1. Create a EcoItem
2. Place it

**Expected behavior**
You shouldn't be able to place them down

**Screenshots**
None

**Server Information (please complete the following information):**
- Eco Version: 6.24.2
- EcoItems Version: 3.27.3

**Additional context**
None

**Comment by WillFP** [comment]
Fixed in latest
