### ISSUE TITLE
add_stat stat boosts updating weirdly

### ISSUE THREAD

**Issue by PrimalPower** [Auxilor/EcoItems#24]
If you switch from an item that gives an aurelium skills stat boost to another item that gives an aurelium skills stat boost directly it will not update the boost. This problem will not happen if you hold a item that doesn't give a stat boost in between (i don't know if this will also happen with  ecoskills. I am also unsure if it is with all permanent effects or just add_stat)

**To Reproduce**
1. Install aurelium skills
2. Create an item that grants 40 toughness using add_star (can be any stat and any number)
3. Create an item that grants 40 strength using add_star (can be any stat and any number)
4. If you put them next to each other in hotbar and start by holding the 40 toughness one, you will get 40 toughness. If you switch directly to the 40 strength one, it will keep the 40 toughness and not give 40 strength (and vice versa). 

**Expected behavior**
When I switch I will lose 40 toughness and gain the 40 strength

**Edit**
When switching directly between stat boosting items it can act completely unpredictably if they both share a stat and one of the items gives an extra stat

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-177 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2e99e5e)
You are 20 version(s) behind
Download the new version at: https://papermc.io/downloads
Previous version: git-Paper-194 (MC: 1.18.1)

- Version of plugin:
- Eco: 6.24.2
- Ecoitems: 3.27.1

**Comment by WillFP** [comment]
I think this is down to how AureliumSkills handles things, because I do the same with EcoSkills and it works fine

**Comment by PrimalPower** [comment]
> I think this is down to how AureliumSkills handles things, because I do the same with EcoSkills and it works fine

I found that it was because Aurelium Skills commands blocks the modifier if a modifier with same name already exists instead of overriding
