### ISSUE TITLE
Crafting recipes with more than one item per slot broken by latest eco (I think)

### ISSUE THREAD

**Issue by KermX** [Auxilor/EcoItems#26]
**Describe the bug**
Crafting recipes that require more than one item per slot appear to not be working. Clicking the item results in it disappearing. No console errors present on startup, reload, or craft.

**To Reproduce**
1. Create an item with a stack of any size as part of the recipe.
2. attempt to craft.

**Expected behavior**
This not to happen

**Screenshots**
Attached video. See also discord ticket #ecoitems-0023

**Server Information (please complete the following information):**
server ver: Paper-198
ecoitems: 3.27.7
eco: 6.24.3

**Additional context**

https://user-images.githubusercontent.com/94108444/154264180-372dc9f1-fb38-44d1-beda-a4141877cb1c.mp4

**Comment by PrimalPower** [comment]
i have this problem too

**Comment by WillFP** [comment]
Fixed in latest eco
