### ISSUE TITLE
Effective Durability doesn't work

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/EcoItems#28]
**Describe the bug**
Changing effective durability on item config won't change anything.

**To Reproduce**
1. Change item.effectiveDurability from any item to any value you want;
2. Restart the server (or reload the plugin etc);
3. Try it out.

**Expected behavior**
Durabillity should be different from the vanilla item's durability based on the value set in the config.

**Server Information (please complete the following information):**
- Version: git-Purpur-1564 (MC: 1.18.1)
- Version of plugin and eco: Eco 6.25.2, Ecoitems 3.29.0

**Comment by WillFP** [comment]
Effective durability works like unbreaking; doesn't change the value shown to the player (as its hardcoded) and instead makes the durability decrease slower/faster, ie if an item has 400 durability in minecraft but you set the effective durability to 800 then it will decrease half as quickly
