### ISSUE TITLE
Custom ore, wood does not work with auto-smelt

### ISSUE THREAD

**Issue by MrJorman** [Auxilor/EcoItems#34]
I use the Items adder plugin and I have my own ore there, silver ore, which if melted will turn out to be a silver ingot, but I use a pickaxe with Auto-smelt and I don't get ore remelting, and also if I break wood I don't get charcoal. And also if I put a block of creativity or survival, I don't get a remelting. Your auto-smelt is completely broken, please fix it and make sure that the CustomCrafting plugin if there is a craft of remelting my recipe, then auto-smelting could read what will come out of the ore block.

**Comment by WillFP** [comment]
Auto-smelt works by running through all furnace recipes, if itemsadder doesn't register the recipe then it can't work
