### ISSUE TITLE
When you modify an item material, that it update the items already crafted

### ISSUE THREAD

**Issue by iSeitan** [Auxilor/EcoItems#40]
**Is your feature request related to a problem? Please describe.**
Currently if you change an item material it doesnt update for those that already have the item crafted

**Describe the solution you'd like**
When you modify an item material, that it update the items already crafted
Currently we have to use a exchange system with shopkeeper and its not working great

**Comment by WillFP** [comment]
I'm not sure how well I could implement that, because the display is done via packets, and updating the material would be server-side
