### ISSUE TITLE
[Bug] Protected area incompatibility (Worldguard, Lands, Griefprevention, etc)

### ISSUE THREAD

**Issue by ghost** [Auxilor/EcoItems#65]
### **Describe the bug**
For all un-opped people, EcoItems items using the trigger **alt_click** does not work in any protected area (such as [Worldguard](https://dev.bukkit.org/projects/worldguard/files) & [Lands](https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-19-support.53313/))

### **Possible solution:** 
- Make `alt_click` not check if the player has building permissions.

### **To Reproduce**
-  Stay in a region-protected area as an un-opped player and use the item using alt_click trigger.

### Steps to reproduce the behavior: 
1. Install [Purpur 1.18.2 ](https://purpurmc.org/downloads/1.18.2)
2. Download [Worldguard](https://dev.bukkit.org/projects/worldguard/files) **or** [Lands](https://www.spigotmc.org/resources/lands-land-claim-plugin-grief-prevention-protection-gui-management-nations-wars-1-19-support.53313/)
3. Download [Worldedit](https://dev.bukkit.org/projects/worldedit/files) for the Worldguard to work
4. Put them in the plugins folder
5. Restart the server
6. Create a protected land (Worldguard: `//wand` -> `select area` -> `/region claim Test`)
7. Create an item that uses the **alt_click** trigger (or use [my config](https://pastebin.com/NvdB0WHw))
8. Reload the plugin: (`/ecoitems reload`)
9. Give yourself the item: (`/ecoitems give YourUsername 1_gem 1`)
10. Un-OP yourself (`/deop YourUsername`)
11. Use the item inside the protected area
 
 
### **Expected behavior**
- When a user alt clicks with the item in a protected area, it should trigger the chain instead of just canceling the action.

**Server Information:**
- Version: Purpur-1632 (MC: 1.18.2)*
- EcoItems version: 3.72.0
- Eco version: 6.36.4

### **Additional context**
Console errors from EcoItems/Eco: **N/A**
Console errors from other plugins: **N/A**

**Comment by WillFP** [comment]
add `disable_antigrief_check: true` to the args

**Comment by StevenW-1** [comment]
I can't figure out where the correct area is to add the `disable_antigrief_check: true`
I've tried a lot of areas and reloaded the plugin but it's not working @WillFP
